### ISSUE TITLE
[FEATURE] Benchmark owner should invite data owners to associate

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#193] opened 2022-06-30 21:53 UTC
**Is your feature request related to a problem? Please describe.**
An association requests usually executes a compatibility test, which then outputs results that are sent back to the benchmark owner for verification and association approval. This workflow breaks when the Benchmark owner is the one that initiates the association. He can't execute the test, since he doesn't have access to the data. Additionally, he won't be able to check back for the results and ensure the integrity of the association

**Describe the solution you'd like**
A benchmark owner, instead of initiating and association, he should "encourage" or "invite" the other party to create an association. That way the compatibility test and results would follow the expected flow.

**Describe alternatives you've considered**
The compatibility test could be skipped at the time of creating an association, and mark the association as "pending test". I find the "invite" model cleaner, as it keeps most of the current model, and doesn't require extra fields or checks to complete an association.

**Comment by hasan7n** [comment] 2023-05-05 17:02
duplicate of #264

**Closed by hasan7n** 2023-05-05 17:02 UTC
Labels: enhancement, cli, server, long-term
